### PR TITLE
Update windows.nim

### PR DESCRIPTION
**Pull request by lithiumfrost**
Free allocated Win32 buffer

### CODE REVIEW

**Comment by lithiumfrost** [comment]
Proposed fix for Issue 16

**Comment by iffy** [comment]
Thanks for the PR! I don't have a Windows machine handy to see why the tests are failing. Can you take a look?

**Comment by lithiumfrost** [comment]
Apologies. Rocky start to my first ever OSS pull request ;-)

That should have been `defer: pcred.unsafeAddr.CredFree` 

Tests in CI should run successfully now with commit revision.

**Comment by iffy** [comment]
No worries; that's how it goes :)

Thank you for this PR!

**Pull request merged**
